server:
  port: 8181

spring:
  application:
    name: lottery-service
  datasource:
    url: jdbc:mysql://124.223.186.153:3306/lottery?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 15980421639xxl,.
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小，最小，最大
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 60000
      test-while-idle: true
      test-on-borrow: true


lottery:
  server-url: http://demo